services:
  tutors-api:
    build: ./api
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - main-network
    volumes:
      - ./api:/src

  # react-app:
  #   build: ./app
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - main-network

networks:
  main-network: